### ISSUE TITLE
Madness level not shown

### ISSUE THREAD

**Issue by Klick3R** [DonnEssime/Custom-Salem#39]
Noticed that the madness level is not shown, i was a part of the current blood moon when it toggled, now after logging in&out the madness level does not show up.

that is a bit alarming considering players that use the client a lot..

**Comment by DonnEssime** [comment]
do you mean that there is no number for you near the faces, that the faces don't change at all, or that even the mouseover of the biles shows madness: 0 ? 

In the first case, trying deleting ~/Salem/bin and updating the client.

**Comment by Klick3R** [comment]
when mouseover the biles there is no madness level. only shows 0

**Comment by DonnEssime** [comment]
then you are not mad :) sure it's the same char? It can also take a while before the server notifies the client of the fact that your character is mad.

**Comment by Klick3R** [comment]
yes it is on my main, and now i did test and long on with vanilla client, apparently 2 levels of madness got removed in a couple of hours.. no idea how, i did not do anything to get madness removed..
maybe a bug in salem itself?

+1 for fast replies

**Comment by Klick3R** [comment]
update: so apparently madness did not update before i studied something .. 
but now it shows, i dont know if it is salem bug or client bug, but at least i now know how to get it to show :)

**Comment by DonnEssime** [comment]
IIRC it will also update when you get an inspiration tick, but if you're at maximum inspiration that's not gonna happen. Known issue, the server only sends madness info after a little while.
