### ISSUE TITLE
Block / Ignore buddy 

### ISSUE THREAD

**Issue by Nsuidara** [DonnEssime/Custom-Salem#44]
Is it possible to add a customer to ignore/block list ?

Mean when we have ignore buddy then we dont got message / not display message from ignore/block person ?

**Comment by LOMS** [comment]
Oh lol, yes. I was about to implement this once. Fastest possible solution I thought about - don't create chat for people with "ignored" substring in name.

**Comment by Nsuidara** [comment]
this solution will be enough for many people :) 

so, if possible implement this :D

**Comment by LOMS** [comment]
Oh, forgot most important part. It should send some message, like, "Sorry, you've been added to my ignore list" on every received message. 
Something like this, putted [here(line 874)](https://github.com/EnderWiggin/Custom-Salem/blob/master/src/haven/ChatUI.java#L874) should work:
if (b.name.contains("ignored")) {
	this.hide();
	this.send("Sorry, you've been added to my ignore list");
}

**Comment by Nsuidara** [comment]
i think better

if (b.name.contains("[ignored]") || b.name.contains("[b]") || b.name.contains("[block]") || b.name.contains("[i]"))

i think, for me can be not resend :)

**Comment by DonnEssime** [comment]
I see some obvious message-loops where two people have eachother blocked and someone sends a kick-off message.

Will look into implementing this (maybe tonight!). It doesn't seem too difficult, and i suppose it might be a life-saver for some people.

I think it will also give a warning, locally, when you try to send a message to someone you have ignored. Probably I will still log all messages that person sends you to file. 

Do note, that this will not stop them from seeing you online. No way I can counter that. It will simply not show the messages you should receive.

**Comment by Nsuidara** [comment]
> Do note, that this will not stop them from seeing you online. No way I can counter that. It will simply not show the messages you should receive.

You know, always less provocation - when you not read :)
